name: Upload Python Package to PyPI

on:
  push:
    tags:
      - 'v*'  # Only run on version tags like v0.1.0

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # ← Required for OIDC / trusted publishing
      contents: read   # ← Optional but recommended
      
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build the package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
